import { useState } from 'react';
import TextField from '@mui/material/TextField';
import Autocomplete from '@mui/material/Autocomplete';
import SearchIcon from '@mui/icons-material/Search';
import IconButton from '@mui/material/IconButton';
import '../CSS/SearchBar.css'
import { Fragment } from 'react';
import TuneIcon from '@mui/icons-material/Tune';
import Popper from '@mui/material/Popper';
import PopperContent from './PopperContent';

export default function SearchBar(props) {
    const [anchorEl, setAnchorEl] = useState(null);
    const [open, setOpen] = useState(false);
    const handleClick = (event) => {
        setAnchorEl(event.currentTarget);
        setOpen(!open);
    };
    const [years, setYears] = useState([2000, 2030])
    // const [years,setYears]=useState([])

    const cancer_types = [
        "Acute Lymphoblastic Leukemia (ALL)",
        "Acute Myeloid Leukemia (AML)",
        "Adolescents, Cancer in",
        "Adrenocortical Carcinoma",
        "AIDS-Related Cancers",
        "Kaposi Sarcoma (Soft Tissue Sarcoma)",
        "AIDS-Related Lymphoma (Lymphoma)",
        "Primary CNS Lymphoma (Lymphoma)",
        "Anal Cancer",
        "Appendix Cancer - see Gastrointestinal Carcinoid Tumors",
        "Astrocytomas, Childhood (Brain Cancer)",
        "Atypical Teratoid/Rhabdoid Tumor, Childhood, Central Nervous System (Brain Cancer)",
        "Basal Cell Carcinoma of the Skin - see Skin Cancer",
        "Bile Duct Cancer",
        "Bladder Cancer",
        "Bone Cancer (includes Ewing Sarcoma and Osteosarcoma and Malignant Fibrous Histiocytoma)",
        "Brain Tumors",
        "Breast Cancer",
        "Bronchial Tumors (Lung Cancer)",
        "Burkitt Lymphoma - see Non-Hodgkin Lymphoma",
        "Carcinoid Tumor (Gastrointestinal)",
        "Carcinoma of Unknown Primary",
        "Central Nervous System",
        "Atypical Teratoid/Rhabdoid Tumor, Childhood (Brain Cancer)",
        "Medulloblastoma and Other CNS Embryonal Tumors, Childhood (Brain Cancer)",
        "Germ Cell Tumor, Childhood (Brain Cancer)",
        "Primary CNS Lymphoma",
        "Cervical Cancer",
        "Childhood Cancers",
        "Childhood Cardiac Tumors Treatment",
        "Cancers of Childhood, Rare",
        "Cholangiocarcinoma - see Bile Duct Cancer",
        "Chordoma, Childhood (Bone Cancer)",
        "Chronic Lymphocytic Leukemia (CLL)",
        "Chronic Myelogenous Leukemia (CML)",
        "Chronic Myeloproliferative Neoplasms",
        "Colorectal Cancer",
        "Craniopharyngioma, Childhood (Brain Cancer)",
        "Cutaneous T-Cell Lymphoma - see Lymphoma (Mycosis Fungoides and Sézary Syndrome)",
        "Ductal Carcinoma In Situ (DCIS) - see Breast Cancer",
        "Embryonal Tumors, Medulloblastoma and Other Central Nervous System, Childhood (Brain Cancer)",
        "Endometrial Cancer (Uterine Cancer)",
        "Ependymoma, Childhood (Brain Cancer)",
        "Esophageal Cancer",
        "Esthesioneuroblastoma (Head and Neck Cancer)",
        "Ewing Sarcoma (Bone Cancer)",
        "Extracranial Germ Cell Tumor, Childhood",
        "Extragonadal Germ Cell Tumor",
        "Eye Cancer",
        "Intraocular Melanoma",
        "Retinoblastoma",
        "Fallopian Tube Cancer",
        "Gallbladder Cancer",
        "Gastric (Stomach) Cancer",
        "Gastrointestinal Carcinoid Tumor",
        "Gastrointestinal Stromal Tumors (GIST) (Soft Tissue Sarcoma)",
        "Germ Cell Tumors",
        "Childhood Central Nervous System Germ Cell Tumors (Brain Cancer)",
        "Childhood Extracranial Germ Cell Tumors",
        "Extragonadal Germ Cell Tumors",
        "Ovarian Germ Cell Tumors",
        "Testicular Cancer",
        "Gestational Trophoblastic Disease",
        "Hairy Cell Leukemia",
        "Head and Neck Cancer",
        "Heart Tumors, Childhood",
        "Hepatocellular (Liver) Cancer",
        "Histiocytosis, Langerhans Cell",
        "Hodgkin Lymphoma",
        "Hypopharyngeal Cancer (Head and Neck Cancer)",
        "Islet Cell Tumors, Pancreatic Neuroendocrine Tumors",
        "Kidney (Renal Cell) Cancer",
        "Langerhans Cell Histiocytosis",
        "Laryngeal Cancer (Head and Neck Cancer)",
        "Leukemia",
        "Lip and Oral Cavity Cancer (Head and Neck Cancer)",
        "Liver Cancer",
        "Lung Cancer (Non-Small Cell, Small Cell, Pleuropulmonary Blastoma, Pulmonary Inflammatory Myofibroblastic Tumor, and Tracheobronchial Tumor)",
        "Lymphoma",
        "Male Breast Cancer",
        "Melanoma",
        "Melanoma, Intraocular (Eye)",
        "Merkel Cell Carcinoma (Skin Cancer)",
        "Mesothelioma, Malignant",
        "Metastatic Cancer",
        "Metastatic Squamous Neck Cancer with Occult Primary (Head and Neck Cancer)",
        "Midline Tract Carcinoma With NUT Gene Changes",
        "Mouth Cancer (Head and Neck Cancer)",
        "Multiple Endocrine Neoplasia Syndromes",
        "Multiple Myeloma/Plasma Cell Neoplasms",
        "Mycosis Fungoides (Lymphoma)",
        "Myelodysplastic Syndromes, Myelodysplastic/Myeloproliferative Neoplasms",
        "Myelogenous Leukemia, Chronic (CML)",
        "Myeloid Leukemia, Acute (AML)",
        "Myeloproliferative Neoplasms, Chronic",
        "Nasal Cavity and Paranasal Sinus Cancer (Head and Neck Cancer)",
        "Nasopharyngeal Cancer (Head and Neck Cancer)",
        "Neuroblastoma",
        "Non-Hodgkin Lymphoma",
        "Non-Small Cell Lung Cancer",
        "Oral Cancer, Lip and Oral Cavity Cancer and Oropharyngeal Cancer (Head and Neck Cancer)",
        "Osteosarcoma and Undifferentiated Pleomorphic Sarcoma of Bone Treatment",
        "Ovarian Cancer",
        "Pancreatic Cancer",
        "Pancreatic Neuroendocrine Tumors (Islet Cell Tumors)",
        "Papillomatosis (Childhood Laryngeal)",
        "Paraganglioma",
        "Paranasal Sinus and Nasal Cavity Cancer (Head and Neck Cancer)",
        "Parathyroid Cancer",
        "Penile Cancer",
        "Pharyngeal Cancer (Head and Neck Cancer)",
        "Pheochromocytoma",
        "Pituitary Tumor",
        "Plasma Cell Neoplasm/Multiple Myeloma",
        "Pleuropulmonary Blastoma (Lung Cancer)",
        "Pregnancy and Breast Cancer",
        "Primary Central Nervous System (CNS) Lymphoma",
        "Primary Peritoneal Cancer",
        "Prostate Cancer",
        "Pulmonary Inflammatory Myofibroblastic Tumor (Lung Cancer)",
        "Rare Cancers of Childhood",
        "Rectal Cancer",
        "Recurrent Cancer",
        "Renal Cell (Kidney) Cancer",
        "Rhabdomyosarcoma, Childhood (Soft Tissue Sarcoma)",
        "Salivary Gland Cancer (Head and Neck Cancer)",
        "Sarcoma",
        "Childhood Rhabdomyosarcoma (Soft Tissue Sarcoma)",
        "Childhood Vascular Tumors (Soft Tissue Sarcoma)",
        "Osteosarcoma (Bone Cancer)",
        "Soft Tissue Sarcoma",
        "Uterine Sarcoma",
        "Sézary Syndrome (Lymphoma)",
        "Skin Cancer",
        "Small Cell Lung Cancer",
        "Small Intestine Cancer",
        "Squamous Cell Carcinoma of the Skin - see Skin Cancer",
        "Squamous Neck Cancer with Occult Primary, Metastatic (Head and Neck Cancer)",
        "Stomach (Gastric) Cancer",
        "T-Cell Lymphoma, Cutaneous - see Lymphoma (Mycosis Fungoides and Sèzary Syndrome)",
        "Throat Cancer (Head and Neck Cancer)",
        "Nasopharyngeal Cancer",
        "Oropharyngeal Cancer",
        "Hypopharyngeal Cancer",
        "Thymoma and Thymic Carcinoma",
        "Thyroid Cancer",
        "Tracheobronchial Tumors (Lung Cancer)",
        "Transitional Cell Cancer of the Renal Pelvis and Ureter (Kidney (Renal Cell) Cancer)",
        "Unknown Primary, Carcinoma of",
        "Ureter and Renal Pelvis, Transitional Cell Cancer (Kidney (Renal Cell) Cancer",
        "Urethral Cancer",
        "Uterine Cancer, Endometrial",
        "Vaginal Cancer",
        "Vascular Tumors (Soft Tissue Sarcoma)",
        "Vulvar Cancer",
        "Wilms Tumor and Other Childhood Kidney Tumors","ABACAVIR",
        "ABEMACICLIB",
        "ABEXINOSTAT",
        "ABIRATERONE",
        "ACALABRUTINIB",
        "ACAMPROSATE",
        "ACARBOSE",
        "ACEBUTOLOL",
        "ACECLIDINE",
        "ACECLOFENAC",
        "ACEGLUTAMIDE",
        "ACEMETACIN",
        "ACENOCOUMAROL",
        "ACETANILIDE",
        "ACETAZOLAMIDE",
        "ACETOHEXAMIDE",
        "ACETOHYDROXAMIC",
        "ACETOHYDROXAMIC  ACID",
        "ACETOHYDROXAMIC ACID",
        "ACETYLCHOLINE",
        "ACETYLCYSTEINE",
        "ACETYLLEUCINE",
        "ACETYLSALICYLIC ACID",
        "ACICLOVIR",
        "ACIPIMOX",
        "ACITRETIN",
        "ACLIDINIUM",
        "ACOTIAMIDE",
        "ACTARIT",
        "ACTIVATED CHARCOAL",
        "ADAPALENE",
        "ADEFOVIR",
        "ADEFOVIR DIPIVOXIL",
        "ADENINE",
        "ADIPHENINE",
        "ADRENALONE",
        "AFATINIB",
        "AFLOQUALONE",
        "AFURESERTIB",
        "AGOMELATINE",
        "AICAR",
        "AJMALINE",
        "ALARELIN",
        "ALBENDAZOLE",
        "ALCAFTADINE",
        "ALECTINIB",
        "ALENDRONATE",
        "ALENDRONIC  ACID",
        "ALENDRONIC ACID",
        "ALFACALCIDOL",
        "ALFUZOSIN",
        "ALIBENDOL",
        "ALIMEMAZINE",
        "ALISERTIB",
        "ALISKIREN",
        "ALIZAPRIDE",
        "ALLOPURINOL",
        "ALLYLTHIOUREA",
        "ALMOTRIPTAN",
        "ALOGLIPTIN",
        "ALOSETRON",
        "ALOXISTATIN",
        "ALPELISIB",
        "ALPHA-1-ANTITRYPSIN",
        "ALPRAZOLAM",
        "ALPROSTADIL",
        "ALTRENOGEST",
        "ALTRETAMINE",
        "ALVELESTAT",
        "ALVERINE",
        "ALVIMOPAN",
        "AMANTADINE",
        "AMBRISENTAN",
        "AMBROXOL",
        "AMENAMEVIR",
        "AMFEBUTAMONE",
        "AMFENAC",
        "AMIFOSTINE",
        "AMIKACIN",
        "AMILORIDE",
        "AMINOGLUTETHIMIDE",
        "AMINOGUANIDINE",
        "AMINOPHYLLINE",
        "AMINOSALICYLIC ACID",
        "AMINOTHIAZOLE",
        "AMIODARONE",
        "AMISULPRIDE",
        "AMITRIPTYLINE",
        "AMLEXANOX",
        "AMLODIPINE",
        "AMODIAQUINE",
        "AMONAFIDE",
        "AMOROLFINE",
        "AMOXAPINE",
        "AMOXICILLIN",
        "AMPHOTERICIN",
        "AMPICILLIN",
        "AMPIROXICAM",
        "AMPRENAVIR",
        "AMPROLIUM",
        "AMSACRINE",
        "AMUVATINIB",
        "AMYLMETACRESOL",
        "ANAGRELIDE",
        "ANAMORELIN",
        "ANASTROZOLE",
        "ANETHOLE TRITHIONE",
        "ANETHOLETRITHIONE",
        "ANGIOTENSIN",
        "ANIDULAFUNGIN",
        "ANIRACETAM",
        "ANISINDIONE",
        "ANISOTROPINE",
        "ANTIMONYL",
        "ANTIPYRINE",
        "APALUTAMIDE",
        "APATINIB?MESYLATE",
        "APIXABAN",
        "APREMILAST",
        "APREPITANT",
        "APROTININ",
        "ARECOLINE",
        "ARFORMOTEROL",
        "ARGATROBAN",
        "ARIPIPRAZOLE",
        "ARMODAFINIL",
        "ARTEMETHER",
        "ARTEMISININ",
        "ARTESUNATE",
        "ARTICAINE",
        "ASENAPINE",
        "ASPARTAME",
        "ASPIRIN",
        "ASTEMIZOLE",
        "ASUNAPREVIR",
        "ATALUREN",
        "ATAZANAVIR",
        "ATENOLOL",
        "ATEZOLIZUMAB",
        "ATIPAMEZOLE",
        "ATOMOXETINE",
        "ATORVASTATIN",
        "ATOSIBAN",
        "ATOVAQUONE",
        "ATRACURIUM",
        "ATROPINE",
        "ATTAPULGITE",
        "AURANOFIN",
        "AVAGACESTAT",
        "AVANAFIL",
        "AVIBACTAM",
        "AVOBENZONE",
        "AXITINIB",
        "AZACITIDINE",
        "AZACYCLONOL",
        "AZAPERONE",
        "AZASETRON",
        "AZATADINE",
        "AZATHIOPRINE",
        "AZELAIC",
        "AZELASTINE",
        "AZELNIDIPINE",
        "AZILSARTAN",
        "AZILSARTAN MEDOXOMIL",
        "AZITHROMYCIN",
        "AZLOCILLIN",
        "AZTREONAM",
        "BACAMPICILLIN",
        "BACITRACIN",
        "BAF312",
        "BAFETINIB",
        "BALOFLOXACIN",
        "BALSALAZIDE",
        "BARASERTIB",
        "BARDOXOLONE",
        "BARICITINIB",
        "BATIMASTAT",
        "BAZEDOXIFENE",
        "BECLOMETHASONE",
        "BEDAQUILINE",
        "BELINOSTAT",
        "BEMEGRIDE",
        "BENACTYZINE",
        "BENAZEPRIL",
        "BENDAMUSTINE",
        "BENDAZAC",
        "BENDROFLUMETHIAZIDE",
        "BENIDIPINE",
        "BENPROPERINE",
        "BENSERAZIDE",
        "BENTIROMIDE",
        "BENZALKONIUM",
        "BENZATROPINE",
        "BENZBROMARONE",
        "BENZETHONIUM",
        "BENZNIDAZOLE",
        "BENZOCAINE",
        "BENZOIC",
        "BENZONATATE",
        "BENZPHETAMINE",
        "BENZTHIAZIDE",
        "BENZTROPINE",
        "BENZYDAMINE",
        "BENZYLPENICILLIN",
        "BEPHENIUM",
        "BEPOTASTINE",
        "BERBERINE",
        "BESIFLOXACIN",
        "BETAHISTINE",
        "BETAINE",
        "BETAMETHASONE",
        "BETAMIPRON",
        "BETAXOLOL",
        "BETHANECHOL",
        "BETRIXABAN",
        "BEVACIZUMAB",
        "BEVANTOLOL",
        "BEXAROTENE",
        "BEZAFIBRATE",
        "BIAPENEM",
        "BICALUTAMIDE",
        "BIFONAZOLE",
        "BILASTINE",
        "BIMATOPROST",
        "BINDARIT",
        "BINIMETINIB",
        "BIPERIDEN",
        "BIRINAPANT",
        "BISACODYL",
        "BISMUTH",
        "BISMUTH SUBGALLATE",
        "BISOPROLOL",
        "BITHIONOL",
        "BITOPERTIN",
        "BIVALIRUDIN",
        "BLEOMYCIN",
        "BOCEPREVIR",
        "BORTEZOMIB",
        "BOSENTAN",
        "BOSUTINIB",
        "BREXPIPRAZOLE",
        "BRIGATINIB",
        "BRIMONIDINE",
        "BRINZOLAMIDE",
        "BRIVARACETAM",
        "BRIVUDINE",
        "BROMAZEPAM",
        "BROMFENAC",
        "BROMHEXINE",
        "BROMISOVAL",
        "BROMOCRIPTINE",
        "BROMPHENIRAMINE",
        "BRONOPOL",
        "BROXYQUINOLINE",
        "BRUCINE",
        "BUCETIN",
        "BUDESONIDE",
        "BUFEXAMAC",
        "BUFLOMEDIL",
        "BUMETANIDE",
        "BUPIVACAINE",
        "BUPROPION",
        "BUSPIRONE",
        "BUSULFAN",
        "BUTABARBITAL",
        "BUTAMBEN",
        "BUTENAFINE",
        "BUTOCONAZOLE",
        "BUTYLPARABEN",
        "BUTYLSCOPOLAMINE",
        "CABAZITAXEL",
        "CABERGOLINE",
        "CABOZANTINIB",
        "CALCIFEDIOL",
        "CALCIPOTRIENE",
        "CALCIUM ACETATE",
        "CALCIUM CARBIMIDE",
        "CALCIUM CITRATE",
        "CALCIUM LACTATE",
        "CALCIUMACETATE",
        "CALCIUMLACTATE",
        "CAMOSTAT",
        "CAMPHOR",
        "CAMRELIZUMAB",
        "CAMYLOFIN",
        "CANAGLIFLOZIN",
        "CANDESARTAN",
        "CANDESARTAN CILEXETIL",
        "CANDESARTANCILEXETIL",
        "CANGRELOR",
        "CAPECITABINE",
        "CAPREOMYCIN",
        "CAPSAICINVANILLOID",
        "CAPTOPRIL",
        "CARBACHOL",
        "CARBADOX",
        "CARBAMAZEPINE",
        "CARBASALATE",
        "CARBAZOCHROME",
        "CARBENICILLIN",
        "CARBENOXOLONE",
        "CARBIDOPA",
        "CARBIMAZOLE",
        "CARBINOXAMINE",
        "CARBOPLATIN",
        "CARBOPROST",
        "CARFILZOMIB",
        "CARGLUMIC ACID",
        "CARIPRAZINE",
        "CARISOPRODOL",
        "CARMOFUR",
        "CARMUSTINE",
        "CARPERITIDE",
        "CARPROFEN",
        "CARSALAM",
        "CARTEOLOL",
        "CARVEDILOL",
        "CARZENIDE",
        "CASPOFUNGIN",
        "CB1954",
        "CEDIRANIB",
        "CEFACLOR",
        "CEFADROXIL",
        "CEFAMANDOLE",
        "CEFAZOLIN",
        "CEFCAPENE",
        "CEFDINIR",
        "CEFDITOREN",
        "CEFEPIME",
        "CEFIXIME",
        "CEFMENOXIME",
        "CEFMETAZOLE",
        "CEFMINOX",
        "CEFONICID",
        "CEFOPERAZONE",
        "CEFORANIDE",
        "CEFOSELIS",
        "CEFOTAXIME",
        "CEFOTIAM",
        "CEFOXITIN",
        "CEFOZOPRAN",
        "CEFPIRAMIDE",
        "CEFPIROME",
        "CEFPODOXIME",
        "CEFRADINE",
        "CEFTAZIDIME",
        "CEFTIBUTEN",
        "CEFTIOFUR",
        "CEFTIZOXIME",
        "CEFTRIAXONE",
        "CEFUROXIME",
        "CELECOXIB",
        "CEPHALEXIN",
        "CEPHALOTHIN",
        "CEPHAPIRIN",
        "CEPHARANTHINE",
        "CEPHRADINE",
        "CERDULATINIB",
        "CERITINIB",
        "CERIVASTATIN",
        "CETILISTAT",
        "CETIRIZINE",
        "CETRIMONIUM",
        "CETYLPYRIDINIUM",
        "CEVIMELINE",
        "CHENODEOXYCHOLIC",
        "CHENODEOXYCHOLIC ACID",
        "CHLORAL HYDRATE",
        "CHLORALHYDRATE",
        "CHLORAMBUCIL",
        "CHLORAMPHENICOL",
        "CHLORCYCLIZINE",
        "CHLORDIAZEPOXIDE",
        "CHLORHEXIDINE",
        "CHLORMADINONE",
        "CHLORMEZANONE",
        "CHLOROAMBUCIL",
        "CHLOROCRESOL",
        "CHLOROPROCAINE",
        "CHLOROQUINE",
        "CHLOROTHIAZIDE",
        "CHLOROTRIANISENE",
        "CHLOROXINE",
        "CHLOROXYLENOL",
        "CHLORPHENAMINE",
        "CHLORPHENIRAMINE",
        "CHLORPROMAZINE",
        "CHLORPROPAMIDE",
        "CHLORPROTHIXENE",
        "CHLORQUINALDOL",
        "CHLORTETRACYCLINE",
        "CHLORTHALIDONE",
        "CHLORZOXAZONE",
        "CHOLECALCIFEROL",
        "CHOLIC",
        "CHOLIC ACID",
        "CHOLINE",
        "CHONDROITIN",
        "CHROMIUM",
        "CHROMOCARB",
        "CICLESONIDE",
        "CICLOPIROX",
        "CIDOFOVIR",
        "CILASTATIN",
        "CILAZAPRIL",
        "CILENGITIDE",
        "CILNIDIPINE",
        "CILOMILAST",
        "CILOSTAZOL",
        "CIMETIDINE",
        "CINACALCET",
        "CINCHOCAINE",
        "CINCHOPHEN",
        "CINEPAZIDE",
        "CINNARIZINE",
        "CINOXACIN",
        "CIPROFIBRATE",
        "CIPROFLOXACIN",
        "CISAPRIDE",
        "CISATRACURIUM",
        "CISPLATIN",
        "CITALOPRAM",
        "CITICOLINE",
        "CITIOLONE",
        "CLADRIBINE",
        "CLARITHROMYCIN",
        "CLEMASTINE",
        "CLEVIDIPINE",
        "CLEVUDINE",
        "CLIDINIUM",
        "CLIMBAZOLE",
        "CLINDAMYCIN",
        "CLINOFIBRATE",
        "CLIOQUINOL",
        "CLOBETASOL",
        "CLOFARABINE",
        "CLOFAZIMINE",
        "CLOFEDANOL",
        "CLOFIBRATE",
        "CLOFIBRIC",
        "CLOFOCTOL",
        "CLOMIFENE",
        "CLOMIPRAMINE",
        "CLONAZEPAM",
        "CLONIDINE",
        "CLOPERASTINE",
        "CLOPIDOGREL",
        "CLOPIDOL",
        "CLORAZEPATE",
        "CLORPRENALINE",
        "CLORSULON",
        "CLOSANTEL",
        "CLOTRIMAZOLE",
        "CLOXACILLIN",
        "CLOXIQUINE",
        "CLOZAPINE",
        "COBICISTAT",
        "COBIMETINIB",
        "CODEINE",
        "COLCHICINE",
        "COLESTILAN CHLORIDE",
        "COLISTIN",
        "CONIVAPTAN",
        "CORTISONE",
        "CORTISONE ACETATE",
        "CORTISONEACETATE",
        "CRENOLANIB",
        "CRISABOROLE",
        "CRIZOTINIB",
        "CUDC-101",
        "CURCUMIN",
        "CYCLANDELATE",
        "CYCLEN",
        "CYCLIZINE",
        "CYCLOBENZAPRINE",
        "CYCLOFENIL",
        "CYCLOPHOSPHAMIDE",
        "CYCLOSPORIN",
        "CYCLOSPORINE",
        "CYPROHEPTADINE",
        "CYPROTERONE",
        "CYPROTERONE ACETATE",
        "CYPROTERONEACETATE",
        "CYROMAZINE",
        "CYSTEAMINE",
        "CYTARABINE",
        "CYTISINE",
        "DABIGATRAN",
        "DABIGATRAN ETEXILATE",
        "DABIGATRANETEXILATE",
        "DABRAFENIB",
        "DACARBAZINE",
        "DACLATASVIR",
        "DACOMITINIB",
        "DALBAVANCIN",
        "DALFAMPRIDINE",
        "DANAZOL",
        "DANOFLOXACIN",
        "DANTHRON",
        "DANTROLENE",
        "DAPAGLIFLOZIN",
        "DAPIPRAZOLE",
        "DAPOXETINE",
        "DAPSON",
        "DAPTOMYCIN",
        "DARIFENACIN",
        "DARUNAVIR",
        "DASABUVIR",
        "DASABUVIRABT-333",
        "DASATINIB",
        "DAUNORUBICIN",
        "D-CYCLOSERINE",
        "DECAMETHONIUM",
        "DECITABINE",
        "DEET",
        "DEFACTINIB",
        "DEFERASIROX",
        "DEFERIPRONE",
        "DEFLAZACORT",
        "DEHYDROACETIC",
        "DEHYDROCHOLIC",
        "DEHYDROCHOLIC ACID",
        "DEHYDROEPIANDROSTERONE",
        "DELAMANID",
        "DELANZOMIB",
        "DELAPRIL",
        "DELAVIRDINE",
        "DEMECLOCYCLINE",
        "DEOXYCHOLIC",
        "DEOXYCORTICOSTERONE",
        "DESIPRAMINE",
        "DESLORATADINE",
        "DESMOPRESSIN",
        "DESOGESTREL",
        "DESONIDE",
        "DESVENLAFAXINE",
        "DETOMIDINE",
        "DEUTETRABENAZINE",
        "DEXAMETHASONE",
        "DEXBROMPHENIRAMINE",
        "DEXLANSOPRAZOLE",
        "DEXMEDETOMIDINE",
        "DEXMETHYLPHENIDATE",
        "DEXRAZOXANE",
        "DEXTROAMPHETAMINE",
        "DEXTROMETHORPHAN",
        "DEXTROPROPOXYPHENE",
        "DEXTROTHYROXINE",
        "DIACEREIN",
        "DIASTASE",
        "DIATRIZOATE",
        "DIAZOXIDE",
        "DIBUCAINE",
        "DIBUTYRYL-CAMP",
        "DICHLOROPHENE",
        "DICHLORPHENAMIDE",
        "DICLAZURIL",
        "DICLOFENAC",
        "DICLOFENAMIDE",
        "DICLOXACILLIN",
        "DICOUMAROL",
        "DICYCLOMINE",
        "DIDANOSINE",
        "DIENOGEST",
        "DIETHYLCARBAMAZINE",
        "DIETHYLPROPION",
        "DIETHYLSTILBESTROL",
        "DIFLORASONE",
        "DIFLOXACIN",
        "DIFLUCORTOLONE",
        "DIFLUNISAL",
        "DIFLUPREDNATE",
        "DIGITOXIN",
        "DIGOXIN",
        "DIHYDRALAZINE",
        "DIHYDROARTEMISININ",
        "DIHYDROSTREPTOMYCIN",
        "DIHYDROTACHYSTEROL",
        "DIIODOHYDROXYQUINOLINE",
        "DILTIAZEM",
        "DIMEMORFAN",
        "DIMENHYDRINATE",
        "DIMESNA",
        "DIMETHYL FUMARATE",
        "DIMETHYLFUMARATE",
        "DINACICLIB",
        "DINITOLMIDE",
        "DINOPROST",
        "DIOSMIN",
        "DIPERODON",
        "DIPHEMANIL",
        "DIPHENHYDRAMINE",
        "DIPHENIDOL",
        "DIPHENYLPYRALINE",
        "DIPYRIDAMOLE",
        "DIRITHROMYCIN",
        "DISOPYRAMIDE",
        "DISULFIRAM",
        "DITHRANOL",
        "DIVALPROEX",
        "DOCETAXEL",
        "DOCUSATE",
        "DOFETILIDE",
        "DOLASETRON",
        "DOLUTEGRAVIR",
        "DOMIPHEN",
        "DOMPERIDONE",
        "DONEPEZIL",
        "DOPAMINE",
        "DORAMAPIMOD",
        "DORIPENEM",
        "DORZOLAMIDE",
        "DOVITINIB",
        "DOXAPRAM",
        "DOXAZOSIN",
        "DOXEPIN",
        "DOXERCALCIFEROL",
        "DOXIFLURIDINE",
        "DOXOFYLLINE",
        "DOXORUBICIN",
        "DOXYCYCLINE",
        "DOXYLAMINE",
        "DRONABINOL",
        "DRONEDARONE",
        "DROPERIDOL",
        "DROPROPIZINE",
        "DROSPIRENONE",
        "DROXIDOPA",
        "DULOXETINE",
        "DURVALUMAB",
        "DUTASTERIDE",
        "DUVELISIB",
        "DYCLONINE",
        "DYPHYLLINE",
        "EBASTINE",
        "ECABET",
        "ECONAZOLE",
        "EDARAVONE",
        "EDOXABAN",
        "EFAVIRENZ",
        "EFINACONAZOLE",
        "EFLORNITHINE",
        "EFONIDIPINE",
        "ELACRIDAR",
        "ELAGOLIX",
        "ELBASVIR",
        "ELETRIPTAN",
        "ELIGLUSTAT",
        "ELLAGIC",
        "ELTROMBOPAG",
        "ELUXADOLINE",
        "ELVITEGRAVIR",
        "EMEDASTINE",
        "EMPAGLIFLOZIN",
        "EMRICASAN",
        "EMTANSINE",
        "EMTRICITABINE",
        "ENALAPRIL",
        "ENALAPRILAT",
        "ENASIDENIB",
        "ENCORAFENIB",
        "ENOXACIN",
        "ENOXAPARIN",
        "ENOXOLONE",
        "ENROFLOXACIN",
        "ENTACAPONE",
        "ENTECAVIR",
        "ENTINOSTAT",
        "ENTOSPLETINIB",
        "ENTRECTINIB",
        "ENZALUTAMIDE",
        "ENZASTAURIN",
        "EPACADOSTAT",
        "EPALRESTAT",
        "EPERISONE",
        "EPINASTINE",
        "EPINEPHRINE",
        "EPIRUBICIN",
        "EPLERENONE",
        "EPRAZINONE",
        "EPRODISATE",
        "EPROSARTAN",
        "EPTIFIBATIDE",
        "ERDOSTEINE",
        "ERGONOVINE",
        "ERLOTINIB",
        "ERTAPENEM",
        "ERTUGLIFLOZIN",
        "ERYTHROMYCIN",
        "ESCIN",
        "ESCITALOPRAM",
        "ESLICARBAZEPINE",
        "ESLICARBAZEPINE ACETATE",
        "ESMOLOL",
        "ESOMEPRAZOLE",
        "ESTAZOLAM",
        "ESTRADIOL",
        "ESTRAMUSTINE",
        "ESTRIOL",
        "ESTRONE",
        "ESTRONE SULFATE",
        "ESTRONESULFATE",
        "ESTROPIPATE",
        "ESZOPICLONE",
        "ETACRYNIC ACID",
        "ETHACRIDINE",
        "ETHAMBUTOL",
        "ETHAMSYLATE",
        "ETHCHLORVYNOL",
        "ETHINYL",
        "ETHINYL ESTRADIOL",
        "ETHINYLESTRADIOL",
        "ETHIONAMIDE",
        "ETHOPROPAZINE",
        "ETHOSUXIMIDE",
        "ETHOTOIN",
        "ETHOXZOLAMIDE",
        "ETHYLPARABEN",
        "ETHYNODIOL",
        "ETIDRONATE",
        "ETODOLAC",
        "ETOFIBRATE",
        "ETOMIDATE",
        "ETONOGESTREL",
        "ETOPOSIDE",
        "ETORICOXIB",
        "ETRAVIRINE",
        "ETRETINATE",
        "EVACETRAPIB",
        "EVEROLIMUS",
        "EVOFOSFAMIDE",
        "EXEMESTANE",
        "EZETIMIBE",
        "EZOGABINE",
        "FAMCICLOVIR",
        "FAMOTIDINE",
        "FAROPENEM",
        "FASUDIL",
        "FAVIPIRAVIR",
        "FEBUXOSTAT",
        "FEDRATINIB",
        "FELBAMATE",
        "FELODIPINE",
        "FENBUFEN",
        "FENFLURAMINE",
        "FENIPENTOL",
        "FENOFIBRATE",
        "FENOFIBRIC",
        "FENOFIBRIC ACID",
        "FENOLDOPAM",
        "FENOPROFEN",
        "FENSPIRIDE",
        "FENTICONAZOLE",
        "FERRIC CATION",
        "FERRICCATION",
        "FERROUS SULFATE",
        "FERROUSSULFATE",
        "FESOTERODINE",
        "FEXOFENADINE",
        "FIDAXOMICIN",
        "FILGOTINIB",
        "FIMASARTAN",
        "FINASTERIDE",
        "FINGOLIMOD",
        "FLAVOPIRIDOL",
        "FLAVOXATE",
        "FLECAINIDE",
        "FLIBANSERIN",
        "FLOCTAFENINE",
        "FLOPROPIONE",
        "FLORFENICOL",
        "FLOXURIDINE",
        "FLUBENDAZOLE",
        "FLUCLOXACILLIN",
        "FLUCONAZOLE",
        "FLUCYTOSINE",
        "FLUDARABINE",
        "FLUDROCORTISONE",
        "FLUFENAMIC",
        "FLUMAZENIL",
        "FLUMEQUINE",
        "FLUMETHASONE",
        "FLUNARIZINE",
        "FLUNIXIN",
        "FLUOCINOLONE",
        "FLUOCINONIDE",
        "FLUOROMETHOLONE",
        "FLUOROURACIL",
        "FLUOXETINE",
        "FLUOXYMESTERONE",
        "FLUPENTHIXOL",
        "FLUPENTIXOL",
        "FLUPHENAZINE",
        "FLUPIRTINE",
        "FLURAZEPAM",
        "FLURBIPROFEN",
        "FLUTAMIDE",
        "FLUTICASONE",
        "FLUVASTATIN",
        "FLUVOXAMINE",
        "FOMEPIZOLE",
        "FONDAPARINUX",
        "FORETINIB",
        "FORMESTANE",
        "FORMOTEROL",
        "FOSAPREPITANT",
        "FOSBRETABULIN",
        "FOSCARNET",
        "FOSFOMYCIN",
        "FOSFOSAL",
        "FOSINOPRIL",
        "FOSTAMATINIB",
        "FROVATRIPTAN",
        "FUDOSTEINE",
        "FULVESTRANT",
        "FUMAGILLIN",
        "FUMARIC",
        "FURALTADONE",
        "FURAZOLIDONE",
        "FUROSEMIDE",
        "FUSIDATE",
        "GABAPENTIN",
        "GABAPENTIN ENACARBIL",
        "GABEXATE",
        "GADODIAMIDE",
        "GADOPENTETATE",
        "GALANTAMINE",
        "GALANTHAMINE",
        "GALETERONE",
        "GALLAMINE",
        "GALLIC",
        "GALUNISERTIB",
        "GANCICLOVIR",
        "GANDOTINIB",
        "GANETESPIB",
        "GATIFLOXACIN",
        "GEFARNATE",
        "GEFITINIB",
        "GEMCITABINE",
        "GEMFIBROZIL",
        "GEMIFLOXACIN",
        "GENISTEIN",
        "GENTAMICIN",
        "GESTODENE",
        "GHRP-2",
        "GIMERACIL",
        "GLAFENINE",
        "GLICLAZIDE",
        "GLIMEPIRIDE",
        "GLIPIZIDE",
        "GLIQUIDONE",
        "GLUCAGON",
        "GLYBURIDE",
        "GLYCOPYRROLATE",
        "GONADORELIN",
        "GRANISETRON",
        "GRAZOPREVIR",
        "GREPAFLOXACIN",
        "GRISEOFULVIN",
        "GUAIACOL",
        "GUAIFENESIN",
        "GUANABENZ",
        "GUANETHIDINE",
        "GUANFACINE",
        "GUANIDINE",
        "HALCINONIDE",
        "HALOBETASOL",
        "HALOFANTRINE",
        "HALOPERIDOL",
        "HALOTHANE",
        "HEPARIN",
        "HEXACHLOROPHENE",
        "HEXAMETHONIUM?DIBROMIDE",
        "HEXESTROL",
        "HEXYLRESORCINOL",
        "HISTAMINE",
        "HOMATROPINE",
        "HUPERZINE",
        "HYDRALAZINE",
        "HYDROCHLOROTHIAZIDE",
        "HYDROCODONE",
        "HYDROCORTISONE",
        "HYDROQUINIDINE",
        "HYDROQUINONE",
        "HYDROXYCHLOROQUINE",
        "HYDROXYHEXAMIDE",
        "HYDROXYPROGESTERONE",
        "HYDROXYUREA",
        "HYDROXYZINE",
        "HYGROMYCIN",
        "HYOSCYAMINE",
        "IBANDRONATE",
        "IBRUTINIB",
        "IBUDILAST",
        "IBUPROFEN",
        "IBUTILIDE",
        "ICOTINIB",
        "IDARUBICIN",
        "IDASANUTLIN",
        "IDEBENONE",
        "IDELALISIB",
        "IDOXURIDINE",
        "IFENPRODIL",
        "IFOSFAMIDE",
        "IGURATIMOD",
        "I-INOSITOL",
        "ILOMASTAT",
        "ILOPERIDONE",
        "IMATINIB",
        "IMIDAFENACIN",
        "IMIDAPRIL",
        "IMIPENEM",
        "IMIPRAMINE",
        "IMIQUIMOD",
        "INDACATEROL",
        "INDAPAMIDE",
        "INDIGO",
        "INDINAVIR",
        "INDOMETACIN",
        "INDOMETHACIN",
        "INIPARIB",
        "INOSINE",
        "INOSINE PRANOBEX",
        "INOSITOL NICOTINATE",
        "INOSITOLNICOTINATE",
        "IODINE",
        "IODIXANOL",
        "IOHEXOL",
        "IOPAMIDOL",
        "IOPANOIC",
        "IOPANOIC ACID",
        "IOPODIC ACID",
        "IOPROMIDE",
        "IOVERSOL",
        "IPILIMUMAB",
        "IPRATROPIUM",
        "IPRIFLAVONE",
        "IRBESARTAN",
        "IRINOTECAN",
        "IRON",
        "IRSOGLADINE",
        "ISAVUCONAZOLE",
        "ISEPAMICIN",
        "ISOCARBOXAZID",
        "ISOCONAZOLE",
        "ISOETHARINE",
        "ISOLEUCINE",
        "ISONIAZID",
        "ISOPRENALINE",
        "ISOSORBIDE",
        "ISOSORBIDE MONONITRATE",
        "ISOSORBIDEMONONITRATE",
        "ISOTRETINOIN",
        "ISOXICAM",
        "ISOXSUPRINE",
        "ISPINESIB",
        "ISRADIPINE",
        "ISTRADEFYLLINE",
        "ITOPRIDE",
        "ITRACONAZOLE",
        "IVABRADINE",
        "IVACAFTOR",
        "IVERMECTIN",
        "IVOSIDENIB",
        "IXABEPILONE",
        "IXAZOMIB",
        "KANAMYCIN",
        "KERATINOCYTE GROWTH FACTOR",
        "KETANSERIN",
        "KETAZOLAM",
        "KETOCONAZOLE",
        "KETOPROFEN",
        "KETOROLAC",
        "KETOTIFEN",
        "L ACIDIPINE",
        "LABETALOL",
        "LACTITOL",
        "LACTOSE",
        "LACTULOSE",
        "LAFUTIDINE",
        "LAMIVUDINE",
        "LAMOTRIGINE",
        "LANDIOLOL",
        "LANOLIN",
        "LANSOPRAZOLE",
        "LANTHANUM CARBONATE",
        "LAPATINIB",
        "LAQUINIMOD",
        "LATAMOXEF",
        "LATANOPROST",
        "L-CARNITINE",
        "L-CYCLOSERINE",
        "LEDIPASVIR",
        "LEFLUNOMIDE",
        "LENALIDOMIDE",
        "LENTINAN",
        "LENVATINIB",
        "LERCANIDIPINE",
        "LESINURAD",
        "LETROZOLE",
        "LEUCOVORIN",
        "LEUPROLIDE",
        "LEUPRORELIN",
        "LEVAMISOLE",
        "LEVETIRACETAM",
        "LEVOBETAXOLOL",
        "LEVOBUPIVACAINE",
        "LEVOCETIRIZINE",
        "LEVODOPA",
        "LEVODROPROPIZINE",
        "LEVOFLOXACIN",
        "LEVOMEFOLIC ACID",
        "LEVOMILNACIPRAN",
        "LEVONORGESTREL",
        "LEVORPHANOL",
        "LEVOSIMENDAN",
        "LEVOSULPIRIDE",
        "LEVOTHYROXINE",
        "LIDOCAINE",
        "LIFITEGRAST",
        "LINAGLIPTIN",
        "LINCOMYCIN",
        "LINEZOLID",
        "LINIFANIB",
        "LINSITINIB",
        "LIOTHYRONINE",
        "LISDEXAMFETAMINE",
        "LISINOPRIL",
        "LITHOCHOLIC",
        "LIXISENATIDE",
        "LOMEFLOXACIN",
        "LOMERIZINE",
        "LOMIBUVIR",
        "LOMITAPIDE",
        "LOMUSTINE",
        "LONAFARNIB",
        "LONIDAMINE",
        "LOPERAMIDE",
        "LOPINAVIR",
        "LORATADINE",
        "LORCASERIN",
        "LORNOXICAM",
        "LOSARTAN",
        "LOSMAPIMOD",
        "LOTEPREDNOL",
        "LOVASTATIN",
        "LOXAPINE",
        "LOXOPROFEN",
        "L-THYROXINE",
        "LUBIPROSTONE",
        "LULICONAZOLE",
        "LUMEFANTRINE",
        "LURASIDONE",
        "LYPRESSIN",
        "MACITENTAN",
        "MAFENIDE",
        "MAGALDRATE",
        "MAGNESIUM OXIDE",
        "MAGNESIUM PIDOLATE",
        "MAGNESIUM SALICYLATE",
        "MAITANSINE",
        "MALOTILATE",
        "MALTOL",
        "MALTOSE",
        "MANIDIPINE",
        "MAPROTILINE",
        "MARAVIROC",
        "MARBOFLOXACIN",
        "MARIMASTAT",
        "MASITINIB",
        "MAZINDOL",
        "MEBENDAZOLE",
        "MEBEVERINE",
        "MECAMYLAMINE",
        "MECARBINATE",
        "MECHLORETHAMINE",
        "MECLIZINE",
        "MECLOFENAMATE",
        "MECLOFENAMIC ACID",
        "MECLOFENOXATE",
        "MEDETOMIDINE",
        "MEDROGESTONE",
        "MEDROXYPROGESTERONE",
        "MEFENAMIC",
        "MEFENAMIC ACID",
        "MEFLOQUINE",
        "MEGESTROL",
        "MEGLUMINE",
        "MELATONIN",
        "MELOXICAM",
        "MELPHALAN",
        "MEMANTINE",
        "MENADIONE",
        "MEPENZOLATE",
        "MEPHENESIN",
        "MEPIVACAINE",
        "MEPREDNISONE",
        "MEPROBAMATE",
        "MEPTAZINOL",
        "MEQUINOL",
        "MERCAPTOPURINE",
        "MEROPENEM",
        "MESALAMINE",
        "MESNA",
        "MESORIDAZINE",
        "MESTRANOL",
        "METAPROTERENOL",
        "METARAMINOL",
        "METAXALONE",
        "METFORMIN",
        "METHACHOLINE",
        "METHACYCLINE",
        "METHADONE",
        "METHAMPHETAMINE",
        "METHAZOLAMIDE",
        "METHENAMINE",
        "METHIMAZOLE",
        "METHOCARBAMOL",
        "METHOTREXATE",
        "METHOTRIMEPRAZINE",
        "METHOXSALEN",
        "METHOXYPHENAMINE",
        "METHSCOPOLAMINE",
        "METHSUXIMIDE",
        "METHYCLOTHIAZIDE",
        "METHYL SCOPOLAMINE BROMIDE",
        "METHYLBENACTYZINE",
        "METHYLDOPA",
        "METHYLERGOMETRINE",
        "METHYLPHENIDATE",
        "METHYLPREDNISOLONE",
        "METHYLSCOPOLAMINE BROMIDE",
        "METHYLTESTOSTERONE",
        "METHYLTHIOURACIL",
        "METHYSERGIDE",
        "METICRANE",
        "METOCLOPRAMIDE",
        "METOLAZONE",
        "METOPROLOL",
        "METRONIDAZOLE",
        "METYRAPONE",
        "METYROSINE",
        "MEVASTATIN",
        "MEXILETINE",
        "MEZLOCILLIN",
        "MIANSERIN",
        "MICAFUNGIN",
        "MICONAZOLE",
        "MIDECAMYCIN",
        "MIDODRINE",
        "MIDOSTAURIN",
        "MIFEPRISTONE",
        "MIGALASTAT",
        "MIGLITOL",
        "MIGLUSTAT",
        "MILNACIPRAN",
        "MILRINONE",
        "MILTEFOSINE",
        "MINAPRINE",
        "MINOCYCLINE",
        "MINOXIDIL",
        "MIRABEGRON",
        "MIRTAZAPINE",
        "MISOPROSTOL",
        "MITOMYCIN",
        "MITOTANE",
        "MITOXANTRONE",
        "MIZORIBINE",
        "MOCETINOSTAT",
        "MOCLOBEMIDE",
        "MODAFINIL",
        "MOEXIPRIL",
        "MOGUISTEINE",
        "MOLIDUSTAT",
        "MOLINDONE",
        "MOLSIDOMINE",
        "MOMETASONE",
        "MONOBENZONE",
        "MONTELUKAST",
        "MOROXYDINE",
        "MOSAPRIDE",
        "MOTOLIMOD",
        "MOXIDECTIN",
        "MOXIFLOXACIN",
        "MOXONIDINE",
        "MOZAVAPTAN",
        "MUBRITINIB",
        "MUPIROCIN",
        "MYCOPHENOLATE",
        "MYCOPHENOLIC",
        "MYCOPHENOLIC ACID",
        "NABILONE",
        "NABUMETONE",
        "NADIFLOXACIN",
        "NADOLOL",
        "NAFAMOSTAT",
        "NAFARELIN",
        "NAFCILLIN",
        "NAFTOPIDIL",
        "NALDEMEDINE",
        "NALIDIXIC",
        "NALIDIXIC ACID",
        "NALMEFENE",
        "NALOXEGOL",
        "NALOXONE",
        "NALTREXONE",
        "NAPABUCASIN",
        "NAPHAZOLINE",
        "NAPROXEN",
        "NARATRIPTAN",
        "NATAMYCIN",
        "NATEGLINIDE",
        "NEBIVOLOL",
        "NEDAPLATIN",
        "NEFAZODONE",
        "NEFIRACETAM",
        "NEFOPAM",
        "NELARABINE",
        "NELFINAVIR",
        "NEOMYCIN",
        "NEOSTIGMINE",
        "NEPAFENAC",
        "NERATINIB",
        "NETICONAZOLE",
        "NETILMICIN",
        "NETUPITANT",
        "NEVIRAPINE",
        "NIALAMIDE",
        "NICARDIPINE",
        "NICORANDIL",
        "NICOTINAMIDE",
        "NICOTINE",
        "NIFEDIPINE",
        "NIFENAZONE",
        "NIFLUMIC",
        "NIFUROXAZIDE",
        "NIKETHAMIDE",
        "NILOTINIB",
        "NILUTAMIDE",
        "NILVADIPINE",
        "NIMESULIDE",
        "NIMODIPINE",
        "NIMUSTINE",
        "NINTEDANIB",
        "NIRAPARIB",
        "NISOLDIPINE",
        "NITAZOXANIDE",
        "NITISINONE",
        "NITRAZEPAM",
        "NITRENDIPINE",
        "NITROFURAL",
        "NITROFURANTOIN",
        "NITROXOLINE",
        "NIVOLUMAB",
        "NIZATIDINE",
        "NONIVAMIDE",
        "NORADRENALINE",
        "NORETHINDRONE",
        "NORETHISTERONE",
        "NORFLOXACIN",
        "NORGESTREL",
        "NORTRIPTYLINE",
        "NORTROPINE",
        "NOVOBIOCIN",
        "NYLIDRIN",
        "NYSTATIN",
        "OBETICHOLIC",
        "OBETICHOLIC ACID",
        "OCLACITINIB?MALEATE",
        "OCTENIDINE",
        "OCTINOXATE",
        "OCTOCRYLENE",
        "OCTREOTIDE",
        "OLANZAPINE",
        "OLAPARIB",
        "OLMESARTAN",
        "OLMUTINIB",
        "OLOPATADINE",
        "OLPRINONE",
        "OLSALAZINE",
        "OLTIPRAZ",
        "OMARIGLIPTIN",
        "OMEPRAZOLE",
        "OMIPALISIB",
        "ONALESPIB",
        "ONDANSETRON",
        "OPICAPONE",
        "ORANTINIB",
        "ORLISTAT",
        "ORNIDAZOLE",
        "OROTIC",
        "ORPHENADRINE",
        "OSELTAMIVIR",
        "OSIMERTINIB",
        "OSPEMIFENE",
        "OTENABANT",
        "OTILONIUM",
        "OUABAIN",
        "OXACEPROL",
        "OXACILLIN",
        "OXALIPLATIN",
        "OXANDROLONE",
        "OXAPROZIN",
        "OXAZEPAM",
        "OXCARBAZEPINE",
        "OXELADIN",
        "OXETHAZAINE",
        "OXFENDAZOLE",
        "OXIDOPAMINE",
        "OXIGLUTATIONE",
        "OXIRACETAM",
        "OXPRENOLOL",
        "OXTRIPHYLLINE",
        "OXYBENZONE",
        "OXYBUPROCAINE",
        "OXYBUTYNIN",
        "OXYCLOZANIDE",
        "OXYMETHOLONE",
        "OXYPHENBUTAZONE",
        "OXYTETRACYCLINE",
        "OXYTOCIN",
        "OZAGREL",
        "OZANIMOD",
        "OZOGAMICIN",
        "PACLITAXEL",
        "PACRITINIB",
        "PALBOCICLIB",
        "PALIPERIDONE",
        "PALONOSETRON",
        "PAMABROM",
        "PAMIDRONATE",
        "PANCURONIUM",
        "PANOBINOSTAT",
        "PANTOPRAZOLE",
        "PARECOXIB",
        "PARGYLINE",
        "PARITAPREVIR",
        "PAROMOMYCIN",
        "PAROXETINE",
        "PASINIAZID",
        "PATUPILONE",
        "PAZOPANIB",
        "PAZUFLOXACIN",
        "PEFLOXACIN",
        "PELITINIB",
        "PEMBROLIZUMAB",
        "PEMETREXED",
        "PEMIROLAST",
        "PEMPIDINE",
        "PENCICLOVIR",
        "PENFLURIDOL",
        "PENICILLAMINE",
        "PENICILLIN",
        "PENTAERYTHRITOL TETRANITRATE",
        "PENTAERYTHRITOLTETRANITRATE",
        "PENTAMIDINE",
        "PENTOSAN POLYSULFATE",
        "PENTOSANPOLYSULFATE",
        "PENTOXIFYLLINE",
        "PENTOXYVERINE",
        "PERAMPANEL",
        "PERGOLIDE",
        "PERINDOPRIL",
        "PERPHENAZINE",
        "PEXIDARTINIB",
        "PEXMETINIB",
        "PHENACETIN",
        "PHENAZOPYRIDINE",
        "PHENDIMETRAZINE",
        "PHENELZINE",
        "PHENFORMIN",
        "PHENINDIONE",
        "PHENIRAMINE",
        "PHENOLPHTHALEIN",
        "PHENOTHIAZINE",
        "PHENOXYBENZAMINE",
        "PHENTERMINE",
        "PHENTOLAMINE",
        "PHENYLBUTAZONE",
        "PHENYLEPHRINE",
        "PHENYTOIN",
        "PHTHALYLSULFACETAMIDE",
        "PICTILISIB",
        "PIDOTIMOD",
        "PILARALISIB",
        "PILOCARPINE",
        "PIMASERTIB",
        "PIMAVANSERIN",
        "PIMECROLIMUS",
        "PIMOBENDAN",
        "PIMOZIDE",
        "PINAVERIUM",
        "PINDOLOL",
        "PIOGLITAZONE",
        "PIPEMIDIC",
        "PIPERACILLIN",
        "PIPERAZINE",
        "PIPERONYL",
        "PIRACETAM",
        "PIRENZEPINE",
        "PIRFENIDONE",
        "PIROMIDIC",
        "PIROXICAM",
        "PITAVASTATIN",
        "PITOLISANT",
        "PIVAMPICILLIN",
        "PIVMECILLINAM",
        "PIXANTRONE",
        "PIZOTIFEN",
        "PLECANATIDE",
        "PLERIXAFOR",
        "POLYMYXIN",
        "POMALIDOMIDE",
        "PONATINIB",
        "PONESIMOD",
        "POSACONAZOLE",
        "POTASSIUM",
        "POTASSIUM GLUCONATE",
        "POTASSIUM PERCHLORATE",
        "POTASSIUMPERCHLORATE",
        "POVIDONE",
        "POZIOTINIB",
        "PRACINOSTAT",
        "PRALATREXATE",
        "PRALIDOXIME",
        "PRAMIPEXOLE",
        "PRAMIRACETAM",
        "PRAMOXINE",
        "PRANLUKAST",
        "PRANOPROFEN",
        "PRASUGREL",
        "PRAVASTATIN",
        "PRAZIQUANTEL",
        "PRAZOSIN",
        "PREDNISOLONE",
        "PREDNISONE",
        "PREGNENOLONE",
        "PRILOCAINE",
        "PRIMAQUINE",
        "PRIMIDONE",
        "PROADIFEN",
        "PROBENECID",
        "PROBUCOL",
        "PROCAINAMIDE",
        "PROCAINE",
        "PROCARBAZINE",
        "PROCHLORPERAZINE",
        "PROCYCLIDINE",
        "PROFLAVINE",
        "PROGESTERONE",
        "PROGUANIL",
        "PROMAZINE",
        "PROMETHAZINE",
        "PROPAFENONE",
        "PROPANTHELINE",
        "PROPARACAINE",
        "PROPERICIAZINE",
        "PROPIVERINE",
        "PROPOFOL",
        "PROPOXYPHENE NAPSYLATE",
        "PROPRANOLOL",
        "PROPYLTHIOURACIL",
        "PROPYPHENAZONE",
        "PROSTAGLANDIN",
        "PROSTAGLANDIN E1",
        "PROTIONAMIDE",
        "PROTIRELIN",
        "PROTRIPTYLINE",
        "PROXYPHYLLINE",
        "PRUCALOPRIDE",
        "PRUSSIAN BLUE",
        "PSEUDOEPHEDRINE",
        "PUROMYCIN",
        "PYRANTEL",
        "PYRAZINAMIDE",
        "PYRIDOSTIGMINE",
        "PYRIDOXAL",
        "PYRIDOXINE",
        "PYRILAMINE",
        "PYRIMETHAMINE",
        "PYRVINIUM",
        "QUAZEPAM",
        "QUETIAPINE",
        "QUINAGOLIDE",
        "QUINAPRIL",
        "QUINESTROL",
        "QUINIDINE",
        "QUININE",
        "QUISINOSTAT",
        "QUIZARTINIB",
        "RABEPRAZOLE",
        "RACECADOTRIL",
        "RACTOPAMINE",
        "RADIATION",
        "RADIOTHERAPY",
        "RADOTINIB",
        "RALIMETINIB",
        "RALOXIFENE",
        "RALTEGRAVIR",
        "RALTITREXED",
        "RAMATROBAN",
        "RAMELTEON",
        "RAMIPRIL",
        "RAMOSETRON",
        "RANITIDINE",
        "RANOLAZINE",
        "RAPAMYCIN",
        "RASAGILINE",
        "RCHOP",
        "REBAMIPIDE",
        "REBEPRAZOLE",
        "REBOXETINE",
        "REGADENOSON",
        "REGORAFENIB",
        "REMDESIVIR",
        "REPAGLINIDE",
        "RESERPINE",
        "RESMINOSTAT",
        "RESORCINOL",
        "RESVERATROL",
        "RETAPAMULIN",
        "RETIGABINE",
        "RIBAVIRIN",
        "RIBOCICLIB",
        "RICOLINOSTAT",
        "RIFABUTIN",
        "RIFAMPIN",
        "RIFAMYCIN",
        "RIFAPENTINE",
        "RIFAXIMIN",
        "RIGOSERTIB",
        "RILPIVIRINE",
        "RILUZOLE",
        "RIMANTADINE",
        "RIMONABANT",
        "RIOCIGUAT",
        "RIPASUDIL",
        "RISEDRONATE",
        "RISPERIDONE",
        "RITODRINE",
        "RITONAVIR",
        "RIVAROXABAN",
        "RIVASTIGMINE",
        "RIZATRIPTAN",
        "ROCILETINIB",
        "ROCURONIUM",
        "ROFECOXIB",
        "ROFLUMILAST",
        "ROLIPRAM",
        "RONIDAZOLE",
        "ROPINIROLE",
        "ROPIVACAINE",
        "ROSCOVITINE",
        "ROSIGLITAZONE",
        "ROSUVASTATIN",
        "ROTIGOTINE",
        "ROXADUSTAT",
        "ROXATIDINE",
        "ROXITHROMYCIN",
        "RUCAPARIB",
        "RUFINAMIDE",
        "RUPATADINE",
        "RUTIN",
        "RUXOLITINIB",
        "SACCHARIN",
        "SACUBITRIL VALSARTAN",
        "SAFINAMIDE",
        "SALBUTAMOL",
        "SALIRASIB",
        "SALMETEROL",
        "SALMON",
        "SALSALATE",
        "SAPROPTERIN",
        "SAQUINAVIR",
        "SARACATINIB",
        "SARAFLOXACIN",
        "SARPOGRELATE",
        "SAXAGLIPTIN",
        "SCOPOLAMINE",
        "SECNIDAZOLE",
        "SECOBARBITAL",
        "SELAMECTIN",
        "SELENIOUS ACID",
        "SELEXIPAG",
        "SELINEXOR",
        "SELISISTAT",
        "SELUMETINIB",
        "SEMAGACESTAT",
        "SERTACONAZOLE",
        "SERTRALINE",
        "SEVELAMER",
        "SIBUTRAMINE",
        "SILDENAFIL",
        "SILIBININ",
        "SILMITASERTIB",
        "SILODOSIN",
        "SIMEPREVIR",
        "SIMVASTATIN",
        "SIROLIMUS",
        "SISOMICIN",
        "SITAFLOXACIN",
        "SITAGLIPTIN",
        "SITAXENTAN",
        "SIVELESTAT",
        "SODIUM TARTRATE",
        "SOFALCONE",
        "SOFOSBUVIR",
        "SOLIFENACIN",
        "SONIDEGIB",
        "SORAFENIB",
        "SOTAGLIFLOZIN",
        "SOTALOL",
        "SOTRASTAURIN",
        "SPARFLOXACIN",
        "SPARTALIZUMAB",
        "SPECTINOMYCIN",
        "SPIRAMYCIN",
        "SPIRONOLACTONE",
        "STAVUDINE",
        "STIRIPENTOL",
        "STREPTOMYCIN",
        "STREPTOZOTOCIN",
        "STRONTIUM RANELATE",
        "STRONTIUMRANELATE",
        "SUCCIMER",
        "SUCCINYLCHOLINE",
        "SUCCINYLSULFATHIAZOLE",
        "SUCRALFATE",
        "SULBACTAM",
        "SULBUTIAMINE",
        "SULCONAZOLE",
        "SULFABENZAMIDE",
        "SULFACETAMIDE",
        "SULFADIAZINE",
        "SULFADOXINE",
        "SULFAGUANIDINE",
        "SULFALENESMPZ",
        "SULFAMERAZINE",
        "SULFAMETER",
        "SULFAMETHAZINE",
        "SULFAMETHIZOLE",
        "SULFAMETHOXAZOLE",
        "SULFAMETHOXYPYRIDAZINE",
        "SULFANILAMIDE",
        "SULFAPHENAZOLE",
        "SULFAPYRIDINE",
        "SULFASALAZINE",
        "SULFATHIAZOLE",
        "SULFINPYRAZONE",
        "SULFISOXAZOLE",
        "SULFOGAIACOL",
        "SULINDAC",
        "SULISOBENZONE",
        "SULPHADIMETHOXINE",
        "SULPIRIDE",
        "SULTAMICILLIN",
        "SUMATRIPTAN",
        "SUNITINIB",
        "SUPROFEN",
        "SUVOREXANT",
        "TACRINE",
        "TACROLIMUS",
        "TADALAFIL",
        "TAFAMIDIS",
        "TAFLUPROST",
        "TAK-700",
        "TALADEGIB",
        "TAMIBAROTENE",
        "TAMOXIFEN",
        "TAMSULOSIN",
        "TANESPIMYCIN",
        "TANNIC",
        "TASIMELTEON",
        "TASISULAM",
        "TAURINE",
        "TAVABOROLE",
        "TAZAROTENE",
        "TAZEMETOSTAT",
        "TAZOBACTAM",
        "TEBIPENEM",
        "TEDIZOLID",
        "TEDIZOLID PHOSPHATE",
        "TEGAFUR",
        "TEGASEROD",
        "TEICOPLANIN",
        "TELAPREVIR",
        "TELBIVUDINE",
        "TELITHROMYCIN",
        "TELMISARTAN",
        "TELOTRISTAT",
        "TELOTRISTAT ETHYL",
        "TEMAZEPAM",
        "TEMOCAPRIL",
        "TEMOZOLOMIDE",
        "TEMSIROLIMUS",
        "TENELIGLIPTIN",
        "TENIPOSIDE",
        "TENOFOVIR",
        "TENOFOVIR ALAFENAMIDE",
        "TENOXICAM",
        "TEPOTINIB",
        "TEPRENONE",
        "TERAZOSIN",
        "TERBINAFINE",
        "TERBUTALINE",
        "TERCONAZOLE",
        "TERFENADINE",
        "TERIFLUNOMIDE",
        "TERLIPRESSIN",
        "TERPIN",
        "TESTOSTERONE",
        "TESTOSTERONE UNDECANOATE",
        "TETRABENAZINE",
        "TETRACAINE",
        "TETRACYCLINE",
        "TETRAHYDROZOLINE",
        "TETRAMISOLE",
        "TEZACAFTORVX-661",
        "THALIDOMIDE",
        "THEOPHYLLINE",
        "THIABENDAZOLE",
        "THIAMINE",
        "THIAMPHENICOL",
        "THIMEROSAL",
        "THIOGUANINE",
        "THIOPROPERAZINE",
        "THIORIDAZINE",
        "THIOTEPA",
        "THIOTHIXENE",
        "THYMOL",
        "TIAGABINE",
        "TIANEPTINE",
        "TIAPROFENIC",
        "TIAPROFENIC ACID",
        "TICAGRELOR",
        "TICARCILLIN",
        "TICLOPIDINE",
        "TIDEGLUSIB",
        "TIGECYCLINE",
        "TILETAMINE",
        "TILMICOSIN",
        "TIMOLOL",
        "TINIDAZOLE",
        "TIOCONAZOLE",
        "TIOGUANINE",
        "TIOPRONIN",
        "TIOTROPIUM",
        "TIOXOLONE",
        "TIPIRACIL",
        "TIRATRICOL",
        "TIROFIBAN",
        "TIVANTINIB",
        "TIVOZANIB",
        "TIZANIDINE",
        "TOBRAMYCIN",
        "TOCAINIDE",
        "TOCOFERSOLAN",
        "TOFACITINIB",
        "TOFOGLIFLOZINCSG",
        "TOLAZAMIDE",
        "TOLAZOLINE",
        "TOLBUTAMIDE",
        "TOLCAPONE",
        "TOLFENAMIC",
        "TOLMETIN",
        "TOLNAFTATE",
        "TOLPERISONE",
        "TOLTERODINE",
        "TOLTRAZURIL",
        "TOLVAPTAN",
        "TOPIRAMATE",
        "TOPIROXOSTAT",
        "TOPOTECAN",
        "TORASEMIDE",
        "TORCETRAPIB",
        "TOREMIFENE",
        "TORSEMIDE",
        "TOZASERTIB",
        "TRABECTEDIN",
        "TRAMADOL",
        "TRAMETINIB",
        "TRANDOLAPRIL",
        "TRANEXAMIC",
        "TRANILAST",
        "TRANYLCYPROMINE",
        "TRAPIDIL",
        "TRAVOPROST",
        "TRAZODONE",
        "TRELAGLIPTIN",
        "TRETINOIN",
        "TRIACETIN",
        "TRIAMCINOLONE",
        "TRIAMTERENE",
        "TRIAZOLAM",
        "TRIBENZAGAN",
        "TRICHLORMETHIAZIDE",
        "TRICIRIBINE",
        "TRICLABENDAZOLE",
        "TRICLOSAN",
        "TRIETHYLENETETRAMINE",
        "TRIFLUOPERAZINE",
        "TRIFLURIDINE",
        "TRIFLUSAL",
        "TRIHEXYPHENIDYL",
        "TRILOSTANE",
        "TRIMEBUTINE",
        "TRIMETAZIDINE",
        "TRIMETHADIONE",
        "TRIMETHOPRIM",
        "TRIMIPRAMINE",
        "TRIOXSALEN",
        "TRIPELENNAMINE",
        "TRIPROLIDINE",
        "TROGLITAZONE",
        "TROMETAMOL",
        "TROPICAMIDE",
        "TROPISETRON",
        "TROSPIUM",
        "TROXERUTIN",
        "TROXIPIDE",
        "TYLOSIN",
        "TYLOXAPOL",
        "UFENAMATE",
        "ULIPRISTAL",
        "ULIXERTINIB",
        "UMECLIDINIUM",
        "URAPIDIL",
        "UREA C-13",
        "URETHANE",
        "URIDINE",
        "URSODEOXYCHOLIC  ACID",
        "URSODEOXYCHOLIC ACID",
        "URSODIOL",
        "VALACICLOVIR",
        "VALBENAZINE",
        "VALDECOXIB",
        "VALGANCICLOVIR",
        "VALNEMULIN",
        "VALPROIC",
        "VALPROIC ACID",
        "VALPROMIDE",
        "VALSARTAN",
        "VANCOMYCIN",
        "VANDETANIB",
        "VARDENAFIL",
        "VARENICLINE",
        "VARLITINIB",
        "VATALANIB",
        "VECURONIUM",
        "VEDOTIN",
        "VELIPARIB",
        "VELPATASVIR",
        "VEMURAFENIB",
        "VENETOCLAX",
        "VENLAFAXINE",
        "VERAPAMIL",
        "VERTEPORFIN",
        "VIDARABINE",
        "VIDOFLUDIMUS",
        "VIGABATRIN",
        "VILANTEROL",
        "VILAZODONE",
        "VILDAGLIPTIN",
        "VINBLASTINE",
        "VINCAMINE",
        "VINCRISTINE",
        "VINORELBINE",
        "VINPOCETINE",
        "VISMODEGIB",
        "VOGLIBOSE",
        "VOLASERTIB",
        "VONOPRAZAN",
        "VORAPAXAR",
        "VORICONAZOLE",
        "VORINOSTAT",
        "VORTIOXETINE",
        "VOXTALISIB",
        "VX-809",
        "WARFARIN",
        "XANTHINOL",
        "XYLAZINE",
        "XYLITOL",
        "XYLOMETAZOLINE",
        "XYLOSE",
        "YM155",
        "YOHIMBINE",
        "ZAFIRLUKAST",
        "ZALCITABINE",
        "ZALEPLON",
        "ZALTOPROFEN",
        "ZANAMIVIR",
        "ZIBOTENTAN",
        "ZIDOVUDINE",
        "ZILEUTON",
        "ZINC GLUCONATE",
        "ZIPRASIDONE",
        "ZOFENOPRIL",
        "ZOLMITRIPTAN",
        "ZONISAMIDE",
        "ZOPICLONE",
        "ZOSUQUIDAR",
        "ZOXAZOLAMINE",
        "ZUCLOPENTHIXOL"
    
    ];

    const handleChange = (e) => {
        if (e.type === 'click')
            props.setValue(e.target.innerHTML)
        else
            props.setValue(e.target.value)
    }
    return (
        <Fragment>
            <Autocomplete
                renderInput={(params) => <TextField {...params} label="Type cancer, treatment or drug" />}
                freeSolo
                options={cancer_types}
                onInputChange={(e) => { handleChange(e) }}
                disableClearable
            />
            <IconButton className='search-icon' onClick={() => { props.goToSearch(props.value,years) }} >
                <SearchIcon size='medium' />
            </IconButton>
            <IconButton onClick={handleClick}>
                <TuneIcon className='filter-icon' size='medium' />
            </IconButton>
            <Popper sx={{zIndex: '1'}} open={open} anchorEl={anchorEl} placement='top' >
                <PopperContent value={years} setValue={setYears}/>
            </Popper>
        </Fragment>
    )
}